class AppLanguages {
  static const List<Map<String, String>> languageList = [
    {"name": "English", "nativeName": "Default", "code": "en"},
    {"name": "Bangla", "nativeName": "বাংলা", "code": "bn"},
    {"name": "Arabic", "nativeName": "العربية", "code": "ar"},
    {"name": "Turkish", "nativeName": "Türkçe", "code": "tr"},
    {"name": "Urdu", "nativeName": "اردو", "code": "ur"},
    {"name": "French", "nativeName": "Français", "code": "fr"},
    {"name": "Spanish", "nativeName": "Español", "code": "es"},
    {"name": "Hindi", "nativeName": "हिन्दी", "code": "hi"},
    {"name": "Indonesian", "nativeName": "Bahasa Indonesia", "code": "id"},
    {"name": "Malay", "nativeName": "Bahasa Melayu", "code": "ms"},
    {"name": "Persian", "nativeName": "فارسی", "code": "fa"},
    {"name": "Russian", "nativeName": "Русский", "code": "ru"},
    {"name": "Portuguese", "nativeName": "Português", "code": "pt"},
    {"name": "German", "nativeName": "Deutsch", "code": "de"},
    {"name": "Italian", "nativeName": "Italiano", "code": "it"},
    {"name": "Chinese (Simplified)", "nativeName": "简体中文", "code": "zh"},
    {"name": "Chinese (Traditional)", "nativeName": "繁體中文", "code": "zh-TW"},
    {"name": "Japanese", "nativeName": "日本語", "code": "ja"},
    {"name": "Korean", "nativeName": "한국어", "code": "ko"},
    {"name": "Swahili", "nativeName": "Kiswahili", "code": "sw"},
    {"name": "Hausa", "nativeName": "Hausa", "code": "ha"},
    {"name": "Tamil", "nativeName": "தமிழ்", "code": "ta"},
    {"name": "Telugu", "nativeName": "తెలుగు", "code": "te"},
    {"name": "Marathi", "nativeName": "मराठी", "code": "mr"},
    {"name": "Vietnamese", "nativeName": "Tiếng Việt", "code": "vi"},
    {"name": "Thai", "nativeName": "ไทย", "code": "th"},
    {"name": "Dutch", "nativeName": "Nederlands", "code": "nl"},
    {"name": "Polish", "nativeName": "Polski", "code": "pl"},
    {"name": "Ukrainian", "nativeName": "Українська", "code": "uk"},
    {"name": "Uzbek", "nativeName": "Oʻzbekcha", "code": "uz"},
    {"name": "Somali", "nativeName": "Soomaaliga", "code": "so"},
    {"name": "Kurdish", "nativeName": "Kurdî", "code": "ku"},
    {"name": "Pashto", "nativeName": "پښتو", "code": "ps"},
    {"name": "Sindhi", "nativeName": "سنڌي", "code": "sd"},
    {"name": "Amharic", "nativeName": "አማርኛ", "code": "am"},
    {"name": "Yoruba", "nativeName": "Yorùbá", "code": "yo"},
    {"name": "Igbo", "nativeName": "Igbo", "code": "ig"},
    {"name": "Oromo", "nativeName": "Afaan Oromoo", "code": "om"},
    {"name": "Azerbaijani", "nativeName": "Azərbaycanca", "code": "az"},
    {"name": "Kazakh", "nativeName": "Қазақ тілі", "code": "kk"},
    {"name": "Chechen", "nativeName": "Нохчийн", "code": "ce"},
    {"name": "Bosnian", "nativeName": "Bosanski", "code": "bs"},
    {"name": "Albanian", "nativeName": "Shqip", "code": "sq"},
    {"name": "Swedish", "nativeName": "Svenska", "code": "sv"},
    {"name": "Norwegian", "nativeName": "Norsk", "code": "no"},
    {"name": "Danish", "nativeName": "Dansk", "code": "da"},
    {"name": "Finnish", "nativeName": "Suomi", "code": "fi"},
    {"name": "Greek", "nativeName": "Ελληνικά", "code": "el"},
    {"name": "Hebrew", "nativeName": "עברית", "code": "he"},
    {"name": "Filipino", "nativeName": "Filipino", "code": "fil"},
    {"name": "Burmese", "nativeName": "မြန်မာစာ", "code": "my"},
    {"name": "Khmer", "nativeName": "ភាសាខ្មែរ", "code": "km"},
    {"name": "Gujarati", "nativeName": "ગુજરાતી", "code": "gu"},
    {"name": "Punjabi", "nativeName": "ਪੰਜਾਬੀ", "code": "pa"},
    {"name": "Malayalam", "nativeName": "മലയാളം", "code": "ml"},
    {"name": "Kannada", "nativeName": "ಕನ್ನಡ", "code": "kn"},
    {"name": "Odia", "nativeName": "ଓଡ଼ିଆ", "code": "or"},
  ];
}
